// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddRepoParams struct {
	RepoID  string `json:"repoId"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type BranchDeleteStatus struct {
	Status string `json:"status"`
}

type FetchRepoParams struct {
	RepoID   []string `json:"repoId"`
	RepoName []string `json:"repoName"`
	RepoPath []string `json:"repoPath"`
}

type GitFolderContentResults struct {
	TrackedFiles     []*string `json:"trackedFiles"`
	FileBasedCommits []*string `json:"fileBasedCommits"`
}

type GitRepoStatusResults struct {
	GitRemoteData        *string   `json:"gitRemoteData"`
	GitRepoName          *string   `json:"gitRepoName"`
	GitBranchList        []*string `json:"gitBranchList"`
	GitAllBranchList     []*string `json:"gitAllBranchList"`
	GitCurrentBranch     *string   `json:"gitCurrentBranch"`
	GitRemoteHost        *string   `json:"gitRemoteHost"`
	GitTotalCommits      *int      `json:"gitTotalCommits"`
	GitLatestCommit      *string   `json:"gitLatestCommit"`
	GitTotalTrackedFiles *int      `json:"gitTotalTrackedFiles"`
}

type HealthCheckParams struct {
	Os  string `json:"os"`
	Git string `json:"git"`
}
