// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddRepoParams struct {
	RepoID  string `json:"repoId"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type FetchRepoParams struct {
	RepoID   []string `json:"repoId"`
	RepoName []string `json:"repoName"`
	RepoPath []string `json:"repoPath"`
}

type HealthCheckParams struct {
	Os  string `json:"os"`
	Git string `json:"git"`
}
